### ISSUE TITLE
data signature does not match function

### ISSUE THREAD

**Issue by ItsShadowl** [TrueFiEng/useDApp#910] opened 2022-07-31 19:49 UTC
**Describe the bug**
`Invalid contract call: data signature does not match function Error. (argument="data", value="0x", code=INVALID_ARGUMENT, version=abi/5.6.4)`

**To Reproduce**
```javascript
const _abi = [
  {
    inputs: [],
    name: 'InconsistentParameterLength',
    type: 'error'
  },
  {
    inputs: [],
    name: 'InvalidToAddress',
    type: 'error'
  },
  {
    inputs: [],
    name: 'NotConfigurator',
    type: 'error'
  },
  {
    inputs: [],
    name: 'NotUpgrader',
    type: 'error'
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'account',
        type: 'address'
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'partner',
        type: 'address'
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'index',
        type: 'uint256'
      }
    ],
    name: 'AccountIndexUpdated',
    type: 'event'
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'previousAdmin',
        type: 'address'
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'newAdmin',
        type: 'address'
      }
    ],
    name: 'AdminChanged',
    type: 'event'
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'beacon',
        type: 'address'
      }
    ],
    name: 'BeaconUpgraded',
    type: 'event'
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint8',
        name: 'version',
        type: 'uint8'
      }
    ],
    name: 'Initialized',
    type: 'event'
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'partner',
        type: 'address'
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'emission',
        type: 'uint256'
      }
    ],
    name: 'RewardEmissionUpdated',
    type: 'event'
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'partner',
        type: 'address'
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'index',
        type: 'uint256'
      }
    ],
    name: 'RewardIndexUpdated',
    type: 'event'
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'account',
        type: 'address'
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256'
      }
    ],
    name: 'RewardsAccrued',
    type: 'event'
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'account',
        type: 'address'
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'to',
        type: 'address'
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256'
      }
    ],
    name: 'RewardsClaimed',
    type: 'event'
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'implementation',
        type: 'address'
      }
    ],
    name: 'Upgraded',
    type: 'event'
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'account',
        type: 'address'
      },
      {
        internalType: 'uint256',
        name: 'totalSupply',
        type: 'uint256'
      },
      {
        internalType: 'uint256',
        name: 'balance',
        type: 'uint256'
      }
    ],
    name: 'accrueRewards',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function'
  },
  {
    inputs: [
      {
        internalType: 'address[]',
        name: 'assets',
        type: 'address[]'
      },
      {
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256'
      },
      {
        internalType: 'address',
        name: 'to',
        type: 'address'
      }
    ],
    name: 'claimRewards',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256'
      }
    ],
    stateMutability: 'nonpayable',
    type: 'function'
  },
  {
    inputs: [
      {
        internalType: 'address[]',
        name: 'assets',
        type: 'address[]'
      },
      {
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256'
      }
    ],
    name: 'claimRewards',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256'
      }
    ],
    stateMutability: 'nonpayable',
    type: 'function'
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'partner',
        type: 'address'
      },
      {
        internalType: 'uint88',
        name: 'emissionPerSecond',
        type: 'uint88'
      }
    ],
    name: 'configureRewardEmission',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function'
  },
  {
    inputs: [
      {
        internalType: 'address[]',
        name: 'partners',
        type: 'address[]'
      },
      {
        internalType: 'uint88[]',
        name: 'emissionsPerSecond',
        type: 'uint88[]'
      }
    ],
    name: 'configureRewardEmissions',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function'
  },
  {
    inputs: [],
    name: 'controller',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address'
      }
    ],
    stateMutability: 'view',
    type: 'function'
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'partner',
        type: 'address'
      }
    ],
    name: 'getDistributionData',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256'
      },
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256'
      },
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256'
      }
    ],
    stateMutability: 'view',
    type: 'function'
  },
  {
    inputs: [],
    name: 'getRewardDistributionEnd',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256'
      }
    ],
    stateMutability: 'view',
    type: 'function'
  },
  {
    inputs: [],
    name: 'getRewardDistributionPerSecond',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256'
      }
    ],
    stateMutability: 'view',
    type: 'function'
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'account',
        type: 'address'
      },
      {
        internalType: 'address',
        name: 'partner',
        type: 'address'
      }
    ],
    name: 'getRewardIndex',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256'
      }
    ],
    stateMutability: 'view',
    type: 'function'
  },
  {
    inputs: [],
    name: 'getRewardToken',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address'
      }
    ],
    stateMutability: 'view',
    type: 'function'
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'account',
        type: 'address'
      },
      {
        internalType: 'address[]',
        name: 'partners',
        type: 'address[]'
      }
    ],
    name: 'getUnclaimedRewards',
    outputs: [
      {
        internalType: 'uint256',
        name: 'unclaimedRewards',
        type: 'uint256'
      }
    ],
    stateMutability: 'view',
    type: 'function'
  },
  {
    inputs: [
      {
        internalType: 'contract ICoreController',
        name: 'coreController',
        type: 'address'
      },
      {
        internalType: 'uint256',
        name: 'totalDistributionPerSecond',
        type: 'uint256'
      },
      {
        internalType: 'uint256',
        name: 'distributionEnd',
        type: 'uint256'
      }
    ],
    name: 'initialize',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function'
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'partner',
        type: 'address'
      }
    ],
    name: 'isRewarded',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool'
      }
    ],
    stateMutability: 'view',
    type: 'function'
  },
  {
    inputs: [],
    name: 'proxiableUUID',
    outputs: [
      {
        internalType: 'bytes32',
        name: '',
        type: 'bytes32'
      }
    ],
    stateMutability: 'view',
    type: 'function'
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'distributionEnd',
        type: 'uint256'
      }
    ],
    name: 'setDistributionEnd',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function'
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'distributionPerSecond',
        type: 'uint256'
      }
    ],
    name: 'setDistributionPerSecond',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function'
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'rewardToken',
        type: 'address'
      }
    ],
    name: 'setRewardToken',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function'
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'newImplementation',
        type: 'address'
      }
    ],
    name: 'upgradeTo',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function'
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'newImplementation',
        type: 'address'
      },
      {
        internalType: 'bytes',
        name: 'data',
        type: 'bytes'
      }
    ],
    name: 'upgradeToAndCall',
    outputs: [],
    stateMutability: 'payable',
    type: 'function'
  }
]
```

I'm interacting with the `getUnclaimedRewards`
There are so many instances where the same interface would work directly with ethers.js but not with useDapp...
This bug is really having high effect on our dev.

**Comment by ItsShadowl** [comment] 2022-07-31 21:59
![image](https://user-images.githubusercontent.com/7571856/182046892-02f64c58-3827-4fac-9ba9-23f3b9426823.png)

It can be reproduced with this contract on Polygon Mumbai: `0xac16Ce6908872859a99c591Fa216b0285255BC26 `with arguments` ['0x60F26ba34d9B41460F4eFCBd3F584a0a144BDEbf',['0xC67caf372Ed92D17195E0b8De0b523c4aCfD8cE8','0xf135D142490E8D267FdbF8EC21618Cb2CB7175C5','0x3a9cF02815F0a6e31b814002c8D553b390b2A6e7']]`

`Error encountered calling 'getUnclaimedRewards' on 0xac16Ce6908872859a99c591Fa216b0285255BC26 with args [0x60F26ba34d9B41460F4eFCBd3F584a0a144BDEbf,0xC67caf372Ed92D17195E0b8De0b523c4aCfD8cE8,0xf135D142490E8D267FdbF8EC21618Cb2CB7175C5,0x3a9cF02815F0a6e31b814002c8D553b390b2A6e7] : data signature does not match function Error. (argument="data", value="0x", code=INVALID_ARGUMENT, version=abi/5.6.4)`

**Comment by ItsShadowl** [comment] 2022-07-31 21:59
@nezouse @tt-marek

**Comment by ItsShadowl** [comment] 2022-07-31 22:00
There are like 5 other instances where it happens, for example just getting a view function that has no parameters.

**Comment by rzadp** [comment] 2022-08-01 13:33
@ItsShadowl Can you point me to a view function, so that I can test it out without the need for interacting with the contract with a write-transaction?

**Comment by ItsShadowl** [comment] 2022-08-01 13:59
Thanks, its very urgent...

**Comment by rzadp** [comment] 2022-08-01 14:26
@ItsShadowl I cannot reproduce the `data signature` issue as seem to be running into a revert on the view function.
Here is excerpt from my code:

```
const config: Config = {
  readOnlyChainId: Mumbai.chainId,
  readOnlyUrls: {
    [Mumbai.chainId]: 'https://rpc-mumbai.maticvigil.com/',
  },
}

const contract = new Contract('0xac16Ce6908872859a99c591Fa216b0285255BC26', _abi)
const rewardsResult = useCall({
    contract,
    method: 'getUnclaimedRewards',
    args: [
      '0x60F26ba34d9B41460F4eFCBd3F584a0a144BDEbf',
      ['0xC67caf372Ed92D17195E0b8De0b523c4aCfD8cE8','0xf135D142490E8D267FdbF8EC21618Cb2CB7175C5','0x3a9cF02815F0a6e31b814002c8D553b390b2A6e7']
    ]
  })
``` 

```
Error: missing revert data in call exception
```

@ItsShadowl Does it make sense to you? Do you have a different call?

**Comment by ItsShadowl** [comment] 2022-08-01 17:26
Thanks for the quick reply, i'm currently investigating it.

> @ItsShadowl I cannot reproduce the `data signature` issue as seem to be running into a revert on the view function. Here is excerpt from my code:
> 
> ```
> const config: Config = {
>   readOnlyChainId: Mumbai.chainId,
>   readOnlyUrls: {
>     [Mumbai.chainId]: 'https://rpc-mumbai.maticvigil.com/',
>   },
> }
> 
> const contract = new Contract('0xac16Ce6908872859a99c591Fa216b0285255BC26', _abi)
> const rewardsResult = useCall({
>     contract,
>     method: 'getUnclaimedRewards',
>     args: [
>       '0x60F26ba34d9B41460F4eFCBd3F584a0a144BDEbf',
>       ['0xC67caf372Ed92D17195E0b8De0b523c4aCfD8cE8','0xf135D142490E8D267FdbF8EC21618Cb2CB7175C5','0x3a9cF02815F0a6e31b814002c8D553b390b2A6e7']
>     ]
>   })
> ```
> 
> ```
> Error: missing revert data in call exception
> ```
> 
> @ItsShadowl Does it make sense to you? Do you have a different call?

**Comment by ItsShadowl** [comment] 2022-08-01 20:37
@rzadp 
Thanks, You are really helpful.

Your claim of it reverting made me research deeper, found it to be the reason for the call failing.

**But why would a reverting call have data signature error?**

Not sure if i should close this or leave it open?

**Comment by rzadp** [comment] 2022-08-04 09:15
> But why would a reverting call have data signature error?
Good question, I don't know.

> Not sure if i should close this or leave it open?
I'll close it now, and we can reopen or create new one if we have something more to act on.

**Closed by rzadp** 2022-08-04 09:15 UTC
Labels: bug
